### ISSUE TITLE
Please Upload 055-assignment

### ISSUE THREAD

**Issue by Nneji123** [Saikat-Basak/Project-on-Bankruptcy-in-Poland#1]
The files in this repository are not complete. Could you please upload 055-assignment in .py or .ipynb format I've been using it for comparisons

**Comment by Saikat-Basak** [comment]
You can find 055-assignment in .py format in my GitHub repository "Project-on-Bankruptcy-in-Taiwan"

**Comment by Nneji123** [comment]
Okay thank you so much

**Comment by Saikat-Basak** [comment]
You are welcome
